apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: nginx-ingress1
spec:
  ingressClassName: nginx
  rules:
  - host: www.simplek8s.com 
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: web1-service
            port:
              number: 80
