apiVersion: v1 
kind: Service
metadata:
  name: web1-service
  namespace: default
spec:
  selector:
    name: web1
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443 
      targetPort: 443 
